### ISSUE TITLE
SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengl");

### ISSUE THREAD

**Issue by HomineLudens** [pokitto/PokittoSim#18]
One of the last commit: 
d4e8a6480a4286b3c2f987cc496ec0061c7ffffa
Broke rendering in Windows. At least in direct mode bitmap. Removing that line restore usual render.

**Comment by pokitto** [comment]
Fixed by @haviital in latest pull. @ensonic would you please check that if you absolutely need the SDL_Hint for Linux then can it be put behind some #ifdef LINUX pre-processor macro`?

**Comment by ensonic** [comment]
It is not linux specific. We need to tests if the requested direct draw mode is supported by the hw instead of just using it. The opengl thing is a workaround since that would convert and 'always' work.
I can't test this right now, since the latest git crashes on linux again ... (looks sound related) - https://gist.github.com/ensonic/02f854710c16e49a42ad3c2b5d463ada

**Comment by pokitto** [comment]
Hi. I am extremely busy at the moment trying to get the hardware out the door. I will take a look at this as soon as I can. The original reason why the audion on Linux crashed was that it begun streaming sound before the output was ready. I am surprised the problem has re-emerged.

**Comment by ensonic** [comment]
Some good news. The audio issue seems to be racyness. The code starts once out of 5 attempts. I'll take a look. When it starts the gfx work, so maybe something changed and we're good with the current option.
