### ISSUE TITLE
wait_ms missing reference?

### ISSUE THREAD

**Issue by HomineLudens** [pokitto/PokittoSim#29]
Just found this function in the code but not sure if it's correctly included.
Best way to fix it?

**Comment by Pharap** [comment]
Are you getting a particular error and do you have a copy of the full error?
Also, is it `wait_ms(int)` or `Simulator::wait_ms(uint16_t)`?
(Both seem to be correctly declared and defined here on the repo: https://github.com/pokitto/PokittoSim/search?utf8=%E2%9C%93&q=wait_ms&type=)

**Comment by HomineLudens** [comment]
it's the one in mbed_sim.cpp so `wait_ms(int)`

Maybe a stupid question, but how can I include it? I got:
`wait.cpp|553|error: 'wait_ms' was not declared in this scope|`

But strange enough intelli-sense suggest it from the code

**Comment by Pharap** [comment]
I assume `wait.cpp` is a file you've written?

Have you tried putting `#include "mbed.h"` or `#include "mbed_sim.h"` at the top of `wait.cpp`?
The path might have to be a bit different, e.g. if `wait.cpp` is at the root level you might have to do `#include "POKITTO_SIM/mbed_sim/mbed_sim.h"`.

And I assume by 'intellisense' you mean you've got this running in Visual Studio rather than Code::Blocks?
Or do you mean Code::Blocks' equivalent of intellisense?

**Comment by HomineLudens** [comment]
#include "mbed.h" fix the problem.

Yes, intellisense for code::blocks (or method completion or what else..) was suggesting me this method without worries about missing include in my cpp file. 

So this seems not to be an issue at all.

Thanks @Pharap  to take some time to dig this out.

**Comment by Pharap** [comment]
No problem, glad it was an easy issue to resolve.

For future reference, anything you want to use in a `.cpp` file has to have its declaration referenced.
The preferred way to do that is usually by including the header that declares it.
(There are other ways, but those other ways have several rules and conditions so I won't discuss them here.)

Also "IntelliSense" is a specific system made by Microsoft for Visual Studio.
The generic term is usually either "code completion" or "autocomplete" (sometimes "auto-complete").
I think "autocomplete" is probably best because I think more people will understand what you mean (even non-programmers).
